"""Lynx — a stateless, type-safe policy kernel for AI agent tool calls.

The single source of truth for the package version is ``__version__`` below;
``pyproject.toml`` reads it dynamically (see ``[tool.hatch.version]``).
"""

from lynx.approvals import (
    ApprovalHandler,
    auto_approve,
    auto_deny,
    callback_approval,
    cli_prompt_approval,
)
from lynx.cancel import Cancelled, CancelToken
from lynx.compressors import (
    Compressor,
    compose_compressors,
    dedup_compressor,
    external_filter_compressor,
    identity_compressor,
    route_compressor,
    truncate_compressor,
)
from lynx.core.scheduler import run_agent
from lynx.core.types import (
    ActionRequest,
    ActionResult,
    ApprovalDecision,
    ApprovalRequest,
    AuditEvent,
    Budget,
    Decision,
    ExecutionContext,
    FinalAnswer,
    Message,
    Principal,
    RunResult,
    ToolCall,
    ToolDef,
    ToolMetadata,
    ToolSet,
    Usage,
    Verdict,
)
from lynx.decorators import shadow, tool
from lynx.durability import (
    DuplicateRecord,
    RunStore,
    RunView,
    StepRecord,
    StepView,
    idempotency_key,
    replay,
    step_record_from_json,
    step_record_to_json,
)
from lynx.executors import (
    Executor,
    inline_executor,
    route_executor,
    subprocess_executor,
)
from lynx.graph import (
    GraphCompileError,
    GraphNode,
    GraphResult,
    GraphSpec,
    NodeOutcome,
    Router,
    compile_graph,
    load_graph_file,
    run_graph,
)
from lynx.policy import (
    PolicyBundle,
    allow,
    approve_required,
    compile_policy,
    deny,
    dry_run,
    load_policy_file,
    transform,
)
from lynx.sdk import Agent, AgentAction
from lynx.sinks import (
    Sink,
    callback_sink,
    jsonl_sink,
    multi_sink,
    noop_sink,
    stdout_sink,
)

__version__ = "2.6.3"

__all__ = [
    "ActionRequest",
    "ActionResult",
    "Agent",
    "AgentAction",
    "ApprovalDecision",
    "ApprovalHandler",
    "ApprovalRequest",
    "AuditEvent",
    "Budget",
    "CancelToken",
    "Cancelled",
    "Compressor",
    "Decision",
    "DuplicateRecord",
    "ExecutionContext",
    "Executor",
    "FinalAnswer",
    "GraphCompileError",
    "GraphNode",
    "GraphResult",
    "GraphSpec",
    "Message",
    "NodeOutcome",
    "PolicyBundle",
    "Principal",
    "Router",
    "RunResult",
    "RunStore",
    "RunView",
    "Sink",
    "StepRecord",
    "StepView",
    "ToolCall",
    "ToolDef",
    "ToolMetadata",
    "ToolSet",
    "Usage",
    "Verdict",
    "__version__",
    "allow",
    "approve_required",
    "auto_approve",
    "auto_deny",
    "callback_approval",
    "callback_sink",
    "cli_prompt_approval",
    "compile_graph",
    "compile_policy",
    "compose_compressors",
    "dedup_compressor",
    "deny",
    "dry_run",
    "external_filter_compressor",
    "idempotency_key",
    "identity_compressor",
    "inline_executor",
    "jsonl_sink",
    "load_graph_file",
    "load_policy_file",
    "multi_sink",
    "noop_sink",
    "replay",
    "route_compressor",
    "route_executor",
    "run_agent",
    "run_graph",
    "shadow",
    "stdout_sink",
    "step_record_from_json",
    "step_record_to_json",
    "subprocess_executor",
    "tool",
    "transform",
    "truncate_compressor",
]
